site_name: Roboy Error Detection
site_description: Module for calculating errors from sensor information as input
theme: readthedocs
pages:
- Index: 'index.md'
- API:
    - 'Motor patterns': 'motor-error-detection.md'
    - 'Joint angle patterns': 'joint-angle-error-detection.md'
- Contribute: 'contribute.md'